stages:
  - clang-format
  - build_linux
  - build_windows
  - unit-tests


image: unityci/editor:ubuntu-2020.3.18f1-base-0.15.0

build_linux:
  stage: build_linux
  retry:
    max: 2
    when: runner_system_failure
  before_script:
    - echo "$UNITY_CERT" > ./Unity_v2020.x.ulf
    - unity-editor -nographics -quit -batchmode -quit -manualLicenseFile ./Unity_v2020.x.ulf || true
  script:
    - mkdir -p $CI_PROJECT_DIR/linux_build
    - unity-editor -nographics -quit -batchmode -projectPath $CI_PROJECT_DIR -buildLinux64Player $CI_PROJECT_DIR/linux_build/build.x86_64
    - zip -r linux_build.zip $CI_PROJECT_DIR/linux_build/
  artifacts:
    paths:
      - linux_build.zip
    expire_in: 1 week

build_windows:
  image:  unityci/editor:ubuntu-2020.3.18f1-windows-mono-0.15.0
  stage: build_windows
  retry:
    max: 2
    when: runner_system_failure
  before_script:
    - echo "$UNITY_CERT" > ./Unity_v2020.x.ulf
    - unity-editor -nographics -quit -batchmode -quit -manualLicenseFile ./Unity_v2020.x.ulf || true
  script:
    - mkdir -p $CI_PROJECT_DIR/windows_build
    - unity-editor -nographics -quit -batchmode -projectPath $CI_PROJECT_DIR -buildWindows64Player $CI_PROJECT_DIR/windows_build/build.x86_64
    - zip -r linux_build.zip $CI_PROJECT_DIR/windows_build/
  artifacts:
    paths:
      - windows_build.zip
    expire_in: 1 week
    
unit-tests:
  stage: unit-tests
  retry:
    max: 2
    when: runner_system_failure
  before_script:
    - echo "$UNITY_CERT" > ./Unity_v2020.x.ulf
    - unity-editor -nographics -quit -batchmode -quit -manualLicenseFile ./Unity_v2020.x.ulf || true
  script:
    - echo "TODO"

clang-format:
  image: ubuntu:latest
  retry:
    max: 2
    when: runner_system_failure
  before_script: 
    - apt-get -qq update && apt-get -qq install clang-format-12
  stage: clang-format
  needs: []
  script:
    - clang-format-12 -i --dry-run `find -type f -name "*.cs" | grep -v Library` -Werror -style=file